nginx:
  image: nginx:1.15.3-alpine
  ports:
    - "4000:4000"
    - "443:4000"
  volumes:
    - ./api-gateway/nginx:/etc/nginx/conf.d
  links:
    - notification:notification
    - user:user
notification:
  build: ./notification-manage
  volumes:
    - ./notification-manage:/btaskee/notification-manage
user:
  build: ./user-manage
  volumes:
    - ./user-manage:/btaskee/user-manage